[build]
    base = "web/"
    publish = "web/dist"
    command = "npm install && npm run build && ls -laR dist/"
    ignore = "git diff --quiet HEAD^ HEAD -- ."

[build.environment]
    YARN_FLAGS = "--no-ignore-optional"
    API_URL = "https://depviz-demo.moul.io/api"

[context.production.environment]
    API_URL = "https://depviz-demo.moul.io/api"
